### PR TITLE
Add support for managing audio speakers

### PR DESCRIPTION
**Pull request by Regaddi**
Similar to allowing to manage cameras and microphones, this PR introduces support for managing audio output devices.

### CODE REVIEW

**Comment by jptaylor** [comment]
@Regaddi this is great. Can we move this to the @daily-co package? RTVI 0.2.1 removes the Daily Transport package from the monorepo. See Changelog for 0.2.1.

**Comment by Regaddi** [comment]
Moved the transport changes to https://github.com/daily-co/realtime-ai-daily/pull/1 👍

**Comment by Regaddi** [comment]
> Closing this since it's part of `@daily-co/realtime-ai-daily` now.

That's possibly a misunderstanding or I am having false assumptions. I think we still need methods on the RTVI client, similar to accessing and updating cam & mic. But the transport-level implementation detail lives in the transport library.

**Review by markbackman — APPROVED** [review]
LGTM!

Can you also update the RTVI docs (web and React) for this change?

**Pull request merged**
